TARGET_PREBUILT_KERNEL := false

DEVICE_PATH := device/amazon/suez
LOCAL_KERNEL := device/amazon/suez-kernel/zImage-dtb

TARGET_BOARD_PLATFORM := mt8173
TARGET_USES_64_BIT_BINDER := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := arm64
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a15

TARGET_NO_BOOTLOADER := true

TARGET_CPU_ABI_LIST := armeabi-v7a,armeabi
TARGET_CPU_ABI_LIST_32_BIT := armeabi-v7a,armeabi
TARGET_CPU_ABI_LIST_64_BIT := arm64-v8a

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive androidboot.unlocked_kernel=true
KERNEL_TOOLCHAIN_PREFIX:= /home/dragon/android-device/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.8/bin/aarch64-linux-android-

BOARD_KERNEL_BASE := 0x40080000
BOARD_KERNEL_OFFSET := 0
BOARD_KERNEL_PAGESIZE := 2048
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x1000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1100000
BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x03400000 --second_offset 0x00e80000 --tags_offset 0x07f80000
# original - not enough space for us!
# BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00000000 --ramdisk_offset 0x03f80000 --second_offset 0x00e80000 --tags_offset 0x07f80000

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1692925952
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2811801600
BOARD_CACHEIMAGE_PARTITION_SIZE := 444596224
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
TARGET_USERIMAGES_USE_EXT4 := true

#TARGET_PREBUILT_KERNEL := $(TOP_DIR)device/amazon/suez-kernel/zImage-dtb
TARGET_KERNEL_SOURCE := $(TOP_DIR)kernel/amazon/suez/kernel
TARGET_KERNEL_CONFIG := $(TOP_DIR)kernel/amazon/suez/arch/arm64/configs/suez_defconfig
TARGET_KERNEL_VARIANT_CONFIG := $(TOP_DIR)kernel/amazon/suez/arch/arm64/configs/suez_defconfig
TARGET_KERNEL_ZIMAGE_OUT := $(TOP_DIR)kernel/amazon/suez/arch/arm64/boot

#TARGET_RECOVERY_INITRC := device/amazon/suez/recovery/root/init.recovery.mt8173.rc
TARGET_RECOVERY_FSTAB := device/amazon/suez/recovery/root/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := ABGR_8888

RECOVERY_SDCARD_ON_DATA := true

TW_THEME := portrait_hdpi
TW_HACKED_BL_BUTTON := true
TW_INCLUDE_L_CRYPTO := true
TARGET_HW_DISK_ENCRYPTION := true

# Panel vsync offsets
PRESENT_TIME_OFFSET_FROM_VSYNC_NS := 0

# Connectivity Combo and GPS
BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_CONNECTIVITY_MODULE := MT6630 
BOARD_MEDIATEK_USES_GPS := true
MTK_COMBO_SUPPORT := yes
MTK_COMBO_CHIP := MT6630
#MTK_COMBO_CHIP := CONSYS_6582
MTK_GPS_SUPPORT := yes
MTK_GPS_CHIP := MTK_GPS_MT6630
BOARD_GPS_LIBRARIES := true
MTK_AGPS_APP := yes
BOARD_AGPS_SUPL_LIBRARIES := true

# Seccomp filters
BOARD_SECCOMP_POLICY := device/amazon/suez/seccomp

ifeq ($(MTK_WLAN_SUPPORT), yes)
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM := /dev/wmtWifi
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P
WIFI_DRIVER_STATE_CTRL_PARAM := /dev/wmtWifi
WIFI_DRIVER_STATE_ON := 1
WIFI_DRIVER_STATE_OFF := 0
endif

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/generic/common/bluetooth
BOARD_HAVE_BLUETOOTH := true

# Graphics
BOARD_EGL_CFG := device/amazon/suez/egl.cfg
TARGET_USES_HWC2 := true
TARGET_USES_HWC2ON1ADAPTER := false
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := false

BOARD_USE_SOFT_GATEKEEPER := true
BOARD_USES_MTK_HARDWARE := true
USE_OPENGL_RENDERER := true
#BOARD_EGL_WORKAROUND_BUG_10194508 := true
#TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
#MAX_VIRTUAL_DISPLAY_DIMENSION := 1 

BOARD_SEPOLICY_DIRS += \
        device/amazon/suez/sepolicy/basic

